// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/hashids/hashids.d.ts
declare namespace Hashids {

    export interface IHashids {
        new(salt: string, minHashLength?: number, alphabet?: string): IHashids;
        version: string;
        minAlphabetLength: number;
        sepDiv: number;
        guardDiv: number;
        errorAlphabetLength: string;
        errorAlphabetSpace: string;
        alphabet: string[];
        seps: string;
        minHashLength: number;
        salt: string;
        decode(hash: string): number[];
        encode(arg: number): string;
        encode(arg: number[]): string;
        encode(...args: number[]): string;
        encodeHex(str: string): string;
        decodeHex(hash: string): string;
        hash(input: number, alphabet: string): string;
        unhash(input: string[], alphabet: string): number;
    }
}

declare module 'hashids' {
    var hashids: Hashids.IHashids;
    export = hashids;
}
